package in.swapnilbhoite.projects.subtitlestudio;

import com.dropbox.client2.DropboxAPI;
import com.dropbox.client2.exception.DropboxException;
import com.dropbox.client2.session.AccessTokenPair;
import com.dropbox.client2.session.AppKeyPair;
import com.dropbox.client2.session.Session;
import com.dropbox.client2.session.WebAuthSession;
import java.awt.Color;
import java.awt.Desktop;
import java.io.*;
import java.net.URI;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Swapnil Bhoite
 */
public class MainWindow extends javax.swing.JFrame implements Runnable {

    public MainWindow() {
        initComponents();

        sync = new Creator();
        sync.setLocationRelativeTo(null);

        cnv = new Convertor();
        cnv.initiateAll();
        cnv.setLocationRelativeTo(null);

        jLabelSubApplicationTitle.setText("Subtitle Studio 3.1");
        jLabelInstructionsTitle.setText("   Move cursor over app name to see details");
        jLabelInstructionsDetailLine1.setText("   - Follow Subtitle Studio to Stay Updated");
        jLabelInstructionsDetailLine2.setText("   - Facebook");
        jLabelInstructionsDetailLine3.setText("   - YouTube Channel");
        jLabelInstructionsDetailLine4.setText("   - Subtitle Studio");
        jLabelInstructionsDetailLine5.setText("   - Contact Developer");
        jLabelInstructionsDetailLine6.setText("");
        jLabelInstructionsDetailLine7.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogUserRegistration = new javax.swing.JDialog();
        jPanelRegistrationParent = new javax.swing.JPanel();
        jPanelRegistrationTitle = new javax.swing.JPanel();
        jLabelRegistrationTitle = new javax.swing.JLabel();
        jLabelRegistrationInstruction = new javax.swing.JLabel();
        jLabelRegistrationName = new javax.swing.JLabel();
        jLabelRegistrationEmail = new javax.swing.JLabel();
        jLabelRegistrationFacebookId = new javax.swing.JLabel();
        jTextFieldRegistrationName = new javax.swing.JTextField();
        jTextFieldRegistrationEmail = new javax.swing.JTextField();
        jTextFieldRegistrationFacebookId = new javax.swing.JTextField();
        jLabelRegistrationFileWarning = new javax.swing.JLabel();
        jButtonRegistrationSubmit = new javax.swing.JButton();
        jDialogWorkInProgress = new javax.swing.JDialog();
        jPanelWorkInProgressParent = new javax.swing.JPanel();
        jLabelWorkInProgressDetails = new javax.swing.JLabel();
        jPanelParent = new javax.swing.JPanel();
        jLabelCover = new javax.swing.JLabel();
        jLabelCreate = new javax.swing.JLabel();
        jLabelConvert = new javax.swing.JLabel();
        jLabelUpload = new javax.swing.JLabel();
        jLabelDownload = new javax.swing.JLabel();
        jLabelSelectApp = new javax.swing.JLabel();
        jLabelSubApplicationTitle = new javax.swing.JLabel();
        jLabelInstructionsTitle = new javax.swing.JLabel();
        jLabelInstructionsDetailLine1 = new javax.swing.JLabel();
        jLabelInstructionsDetailLine2 = new javax.swing.JLabel();
        jLabelInstructionsDetailLine3 = new javax.swing.JLabel();
        jLabelInstructionsDetailLine4 = new javax.swing.JLabel();
        jLabelInstructionsDetailLine5 = new javax.swing.JLabel();
        jLabelInstructionsDetailLine6 = new javax.swing.JLabel();
        jLabelInstructionsDetailLine7 = new javax.swing.JLabel();
        jLabelFacebookPromo = new javax.swing.JLabel();
        jLabelYouTubePromo = new javax.swing.JLabel();

        jDialogUserRegistration.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogUserRegistration.setModal(true);
        jDialogUserRegistration.setResizable(false);
        jDialogUserRegistration.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogUserRegistrationWindowClosing(evt);
            }
        });

        jPanelRegistrationParent.setBackground(new java.awt.Color(51, 51, 51));

        jPanelRegistrationTitle.setBackground(new java.awt.Color(0, 0, 0));

        jLabelRegistrationTitle.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabelRegistrationTitle.setForeground(new java.awt.Color(102, 255, 255));
        jLabelRegistrationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegistrationTitle.setText("One Time Registration");
        jLabelRegistrationTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelRegistrationTitleLayout = new javax.swing.GroupLayout(jPanelRegistrationTitle);
        jPanelRegistrationTitle.setLayout(jPanelRegistrationTitleLayout);
        jPanelRegistrationTitleLayout.setHorizontalGroup(
            jPanelRegistrationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRegistrationTitleLayout.setVerticalGroup(
            jPanelRegistrationTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistrationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelRegistrationInstruction.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrationInstruction.setText("To use online services, just submit this few details for first time only...");

        jLabelRegistrationName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrationName.setText("Your Name - ");

        jLabelRegistrationEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrationEmail.setText("Email -");

        jLabelRegistrationFacebookId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrationFacebookId.setText("Facebook ID (Optional) - ");

        jTextFieldRegistrationName.setText("-");

        jTextFieldRegistrationEmail.setText("-");

        jTextFieldRegistrationFacebookId.setText("-");

        jLabelRegistrationFileWarning.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrationFileWarning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelRegistrationFileWarning.setText("Don't delete \"user.dat\" file, It will contain your registration info...");
        jLabelRegistrationFileWarning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonRegistrationSubmit.setText("Submit");
        jButtonRegistrationSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrationSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRegistrationParentLayout = new javax.swing.GroupLayout(jPanelRegistrationParent);
        jPanelRegistrationParent.setLayout(jPanelRegistrationParentLayout);
        jPanelRegistrationParentLayout.setHorizontalGroup(
            jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButtonRegistrationSubmit)
                    .addComponent(jLabelRegistrationFileWarning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelRegistrationParentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanelRegistrationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(jPanelRegistrationParentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegistrationParentLayout.createSequentialGroup()
                        .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelRegistrationName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRegistrationEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRegistrationFacebookId, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldRegistrationName)
                            .addComponent(jTextFieldRegistrationEmail)
                            .addComponent(jTextFieldRegistrationFacebookId))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRegistrationParentLayout.createSequentialGroup()
                        .addComponent(jLabelRegistrationInstruction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))))
        );
        jPanelRegistrationParentLayout.setVerticalGroup(
            jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrationParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRegistrationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRegistrationInstruction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistrationName)
                    .addComponent(jTextFieldRegistrationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistrationEmail)
                    .addComponent(jTextFieldRegistrationEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRegistrationParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRegistrationFacebookId)
                    .addComponent(jTextFieldRegistrationFacebookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRegistrationSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelRegistrationFileWarning)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogUserRegistrationLayout = new javax.swing.GroupLayout(jDialogUserRegistration.getContentPane());
        jDialogUserRegistration.getContentPane().setLayout(jDialogUserRegistrationLayout);
        jDialogUserRegistrationLayout.setHorizontalGroup(
            jDialogUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegistrationParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogUserRegistrationLayout.setVerticalGroup(
            jDialogUserRegistrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRegistrationParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDialogWorkInProgress.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogWorkInProgress.setModal(true);
        jDialogWorkInProgress.setResizable(false);
        jDialogWorkInProgress.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialogWorkInProgressWindowClosing(evt);
            }
        });

        jPanelWorkInProgressParent.setBackground(new java.awt.Color(51, 51, 51));

        jLabelWorkInProgressDetails.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelWorkInProgressDetails.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWorkInProgressDetails.setText("Please wait, connecting to server(s)...");

        javax.swing.GroupLayout jPanelWorkInProgressParentLayout = new javax.swing.GroupLayout(jPanelWorkInProgressParent);
        jPanelWorkInProgressParent.setLayout(jPanelWorkInProgressParentLayout);
        jPanelWorkInProgressParentLayout.setHorizontalGroup(
            jPanelWorkInProgressParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWorkInProgressParentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelWorkInProgressDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        jPanelWorkInProgressParentLayout.setVerticalGroup(
            jPanelWorkInProgressParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWorkInProgressParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWorkInProgressDetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialogWorkInProgressLayout = new javax.swing.GroupLayout(jDialogWorkInProgress.getContentPane());
        jDialogWorkInProgress.getContentPane().setLayout(jDialogWorkInProgressLayout);
        jDialogWorkInProgressLayout.setHorizontalGroup(
            jDialogWorkInProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWorkInProgressParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialogWorkInProgressLayout.setVerticalGroup(
            jDialogWorkInProgressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelWorkInProgressParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Subtitle Studio 3.1");
        setResizable(false);

        jPanelParent.setBackground(new java.awt.Color(51, 51, 51));

        jLabelCover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/swapnilbhoite/projects/subtitlestudio/resources/800_200.jpg"))); // NOI18N
        jLabelCover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelCreate.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCreate.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabelCreate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCreate.setText("Create");
        jLabelCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCreate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
        });

        jLabelConvert.setBackground(new java.awt.Color(0, 0, 0));
        jLabelConvert.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabelConvert.setForeground(new java.awt.Color(255, 255, 255));
        jLabelConvert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConvert.setText("Convert");
        jLabelConvert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelConvert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelUpload.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUpload.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabelUpload.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUpload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUpload.setText("Upload");
        jLabelUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
        });

        jLabelDownload.setBackground(new java.awt.Color(0, 0, 0));
        jLabelDownload.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabelDownload.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDownload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDownload.setText("Download");
        jLabelDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelSelectApp.setFont(new java.awt.Font("Candara", 0, 18)); // NOI18N
        jLabelSelectApp.setForeground(new java.awt.Color(204, 204, 204));
        jLabelSelectApp.setText("select app ->");

        jLabelSubApplicationTitle.setBackground(new java.awt.Color(51, 51, 51));
        jLabelSubApplicationTitle.setFont(new java.awt.Font("Candara", 0, 24)); // NOI18N
        jLabelSubApplicationTitle.setForeground(new java.awt.Color(51, 204, 255));
        jLabelSubApplicationTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubApplicationTitle.setText("Subtitle Studio 3.1");
        jLabelSubApplicationTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelInstructionsTitle.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsTitle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsTitle.setText("   Move cursor over app name to see details");

        jLabelInstructionsDetailLine1.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine1.setText("   - Follow Subtitle Studio to Stay Updated");

        jLabelInstructionsDetailLine2.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine2.setText("   - Facebook");
        jLabelInstructionsDetailLine2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInstructionsDetailLine2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstructionsDetailLine2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelInstructionsDetailLine3.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine3.setText("   - YouTube Channel");
        jLabelInstructionsDetailLine3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInstructionsDetailLine3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstructionsDetailLine3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelInstructionsDetailLine4.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine4.setText("   - Subtitle Studio");
        jLabelInstructionsDetailLine4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInstructionsDetailLine4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstructionsDetailLine4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelInstructionsDetailLine5.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine5.setText("   - Contact Developer");
        jLabelInstructionsDetailLine5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInstructionsDetailLine5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInstructionsDetailLine5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelInstructionsDetailLine6.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine6.setText("   -");
        jLabelInstructionsDetailLine6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInstructionsDetailLine6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelInstructionsDetailLine7.setBackground(new java.awt.Color(51, 51, 51));
        jLabelInstructionsDetailLine7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelInstructionsDetailLine7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInstructionsDetailLine7.setText("   -");
        jLabelInstructionsDetailLine7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInstructionsDetailLine7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subApplicationLabelMouseExited(evt);
            }
        });

        jLabelFacebookPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/swapnilbhoite/projects/subtitlestudio/resources/fb.jpg"))); // NOI18N
        jLabelFacebookPromo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFacebookPromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFacebookPromoMouseClicked(evt);
            }
        });

        jLabelYouTubePromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/swapnilbhoite/projects/subtitlestudio/resources/yt.png"))); // NOI18N
        jLabelYouTubePromo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelYouTubePromo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelYouTubePromoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelParentLayout = new javax.swing.GroupLayout(jPanelParent);
        jPanelParent.setLayout(jPanelParentLayout);
        jPanelParentLayout.setHorizontalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addComponent(jLabelSelectApp)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCreate)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelConvert)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUpload)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelDownload))
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInstructionsDetailLine1)
                            .addComponent(jLabelInstructionsTitle)
                            .addGroup(jPanelParentLayout.createSequentialGroup()
                                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInstructionsDetailLine5)
                                    .addComponent(jLabelInstructionsDetailLine6)
                                    .addComponent(jLabelInstructionsDetailLine7)
                                    .addComponent(jLabelInstructionsDetailLine4)
                                    .addComponent(jLabelInstructionsDetailLine3)
                                    .addComponent(jLabelInstructionsDetailLine2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelFacebookPromo)
                                    .addComponent(jLabelYouTubePromo)))))
                    .addComponent(jLabelSubApplicationTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelParentLayout.setVerticalGroup(
            jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParentLayout.createSequentialGroup()
                .addComponent(jLabelCover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCreate)
                    .addComponent(jLabelConvert)
                    .addComponent(jLabelUpload)
                    .addComponent(jLabelDownload)
                    .addComponent(jLabelSelectApp))
                .addGap(18, 18, 18)
                .addComponent(jLabelSubApplicationTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParentLayout.createSequentialGroup()
                        .addComponent(jLabelInstructionsTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstructionsDetailLine1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstructionsDetailLine2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstructionsDetailLine3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstructionsDetailLine4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstructionsDetailLine5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelInstructionsDetailLine6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInstructionsDetailLine7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelParentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelYouTubePromo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelFacebookPromo)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subApplicationLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subApplicationLabelMouseEntered
        if (evt.getSource() == jLabelCreate) {
            jLabelCreate.setForeground(Color.cyan);
            jLabelSubApplicationTitle.setText("Lyrics Synchronizer");
            jLabelInstructionsTitle.setText("How to use");
            jLabelInstructionsDetailLine1.setText("   - Add video file");
            jLabelInstructionsDetailLine2.setText("   - Paste lyrics, dialogs");
            jLabelInstructionsDetailLine3.setText("   - Click 'START" + '"' + "dialog initials...' BUTTON or Press Key 's' when dialog starts");
            jLabelInstructionsDetailLine4.setText("   - Click '" + '"' + "...dialog end characters" + '"' + " END' BUTTON or press Key 's' when that dialog ends");
            jLabelInstructionsDetailLine5.setText("   - Subtitle file(videoFileName.srt) will be created in same folder of source video file");
            jLabelInstructionsDetailLine6.setText("   - Finish");
            jLabelInstructionsDetailLine7.setText("");
        }
        if (evt.getSource() == jLabelConvert) {
            jLabelConvert.setForeground(Color.cyan);
            jLabelSubApplicationTitle.setText("Subtitle Converter");
            jLabelInstructionsTitle.setText("Subtitle Converter (How to use)");
            jLabelInstructionsDetailLine1.setText("   - Add .srt subtitle file(s) to convert into .ssa");
            jLabelInstructionsDetailLine2.setText("   - You can add multiple files at a time");
            jLabelInstructionsDetailLine3.setText("   - Choose whatever settings you want");
            jLabelInstructionsDetailLine4.setText("   - Try 'Fade' effect, it's kool animated effect :P");
            jLabelInstructionsDetailLine5.setText("   - Subtitle file(srtFileName.ssa) will be created in same folder of source .srt file");
            jLabelInstructionsDetailLine6.setText("   - *Don't forget to RENAME/MOVE/DELETE the old .srt file,");
            jLabelInstructionsDetailLine7.setText("      otherwise your media player may use .srt instead of new .ssa file");
        }
        if (evt.getSource() == jLabelUpload) {
            jLabelUpload.setForeground(Color.cyan);
            jLabelSubApplicationTitle.setText("Upload Subtitles");
            jLabelInstructionsTitle.setText("Uploader");
            jLabelInstructionsDetailLine1.setText("   - Add subtitle files");
            jLabelInstructionsDetailLine2.setText("   - Enter metadata if available like Title, Artist, Album");
            jLabelInstructionsDetailLine3.setText("   - Click 'Upload'");
            jLabelInstructionsDetailLine4.setText("   - Finish");
            jLabelInstructionsDetailLine5.setText("");
            jLabelInstructionsDetailLine6.setText("");
            jLabelInstructionsDetailLine7.setText("");
        }
        if (evt.getSource() == jLabelDownload) {
            jLabelDownload.setForeground(Color.cyan);
            jLabelSubApplicationTitle.setText("Download Subtitles");
            jLabelInstructionsTitle.setText("Downloader");
            jLabelInstructionsDetailLine1.setText("   - Enter keywords");
            jLabelInstructionsDetailLine2.setText("   - Click 'Search'");
            jLabelInstructionsDetailLine3.setText("   - Select result");
            jLabelInstructionsDetailLine4.setText("   - Click 'Download'");
            jLabelInstructionsDetailLine5.setText("   - Finish");
            jLabelInstructionsDetailLine6.setText("");
            jLabelInstructionsDetailLine7.setText("");
        }
        if (evt.getSource() == jLabelInstructionsDetailLine2) {
            jLabelInstructionsDetailLine2.setForeground(Color.cyan);
        }
        if (evt.getSource() == jLabelInstructionsDetailLine3) {
            jLabelInstructionsDetailLine3.setForeground(Color.cyan);
        }
        if (evt.getSource() == jLabelInstructionsDetailLine4) {
            jLabelInstructionsDetailLine4.setForeground(Color.cyan);
        }
        if (evt.getSource() == jLabelInstructionsDetailLine5) {
            jLabelInstructionsDetailLine5.setForeground(Color.cyan);
        }
        if (evt.getSource() == jLabelInstructionsDetailLine6) {
            jLabelInstructionsDetailLine6.setForeground(Color.cyan);
        }
        if (evt.getSource() == jLabelInstructionsDetailLine7) {
            jLabelInstructionsDetailLine7.setForeground(Color.cyan);
        }
    }//GEN-LAST:event_subApplicationLabelMouseEntered

    private void subApplicationLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subApplicationLabelMouseExited
        jLabelCreate.setForeground(Color.white);
        jLabelConvert.setForeground(Color.white);
        jLabelUpload.setForeground(Color.white);
        jLabelDownload.setForeground(Color.white);
        jLabelInstructionsDetailLine2.setForeground(Color.white);
        jLabelInstructionsDetailLine3.setForeground(Color.white);
        jLabelInstructionsDetailLine4.setForeground(Color.white);
        jLabelInstructionsDetailLine5.setForeground(Color.white);
        jLabelInstructionsDetailLine6.setForeground(Color.white);
        jLabelInstructionsDetailLine7.setForeground(Color.white);
        jLabelSubApplicationTitle.setText("Subtitle Studio 3.1");
        jLabelInstructionsTitle.setText("   Move cursor over app name to see details");
        jLabelInstructionsDetailLine1.setText("   - Follow Subtitle Studio to Stay Updated");
        jLabelInstructionsDetailLine2.setText("   - Facebook");
        jLabelInstructionsDetailLine3.setText("   - YouTube Channel");
        jLabelInstructionsDetailLine4.setText("   - Subtitle Studio");
        jLabelInstructionsDetailLine5.setText("   - Contact Developer");
        jLabelInstructionsDetailLine6.setText("");
        jLabelInstructionsDetailLine7.setText("");
    }//GEN-LAST:event_subApplicationLabelMouseExited

    private void subApplicationLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subApplicationLabelMouseClicked
        if (evt.getSource() == jLabelCreate) {
            this.setVisible(false);
            sync.setVisible(true);
            Creator.jDialog1.setSize(700, 340);
            Creator.jDialog1.setLocationRelativeTo(null);
            Creator.jDialog1.setVisible(true);
        }

        if (evt.getSource() == jLabelConvert) {
            this.setVisible(false);
            cnv.setVisible(true);
        }

        if (evt.getSource() == jLabelUpload) {
            registerUser();
            threadNo = 1;
            new Thread(this).start();
        }

        if (evt.getSource() == jLabelDownload) {
            registerUser();
            threadNo = 2;
            new Thread(this).start();
        }
    }//GEN-LAST:event_subApplicationLabelMouseClicked

    private void jButtonRegistrationSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrationSubmitActionPerformed
        String name = jTextFieldRegistrationName.getText();
        String email = jTextFieldRegistrationEmail.getText();
        String fbid = jTextFieldRegistrationFacebookId.getText();
        if (name.equals("-") || name.equals("") || email.equals("-") || email.equals("")) {
            jLabelRegistrationFileWarning.setText("Please Enter Name & Email...");
        } else {
            try {
                jLabelRegistrationFileWarning.setText("Connecting to Subtitle Studio...");
                AppKeyPair appKeys = new AppKeyPair(APP_KEY, APP_SECRET);
                WebAuthSession session = new WebAuthSession(appKeys, ACCESS_TYPE);
                myDropBox = new DropboxAPI<WebAuthSession>(session);
                AccessTokenPair newAuth = new AccessTokenPair(AUTH_KEY, AUTH_SECRET);
                myDropBox.getSession().setAccessTokenPair(newAuth);

                jLabelRegistrationFileWarning.setText("Requesting Registration...");
                Date d = new Date();
                String content = d + "___" + email + "___" + System.getProperty("user.name") + "___" + name + "___" + fbid;
                ByteArrayInputStream inputStream = new ByteArrayInputStream(content.getBytes());
                try {
                    DropboxAPI.Entry entry1 = myDropBox.putFile("/users/" + content + ".txt", inputStream, content.length(), null, null);
                    jLabelRegistrationFileWarning.setText("Registration Complete...");
                    BufferedWriter writer = new BufferedWriter(new FileWriter("user.dat"));
                    writer.write(content);
                    writer.close();
                    jDialogUserRegistration.dispose();
                } catch (DropboxException ex) {
                    jLabelRegistrationFileWarning.setText("ERROR connecting to network!!!");
                }
            } catch (IOException ex1) {
                System.exit(1);
            }
        }
    }//GEN-LAST:event_jButtonRegistrationSubmitActionPerformed

    private void jDialogUserRegistrationWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogUserRegistrationWindowClosing
        System.exit(0);
    }//GEN-LAST:event_jDialogUserRegistrationWindowClosing

    private void jDialogWorkInProgressWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialogWorkInProgressWindowClosing
        System.exit(0);
    }//GEN-LAST:event_jDialogWorkInProgressWindowClosing

    private void jLabelInstructionsDetailLine2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstructionsDetailLine2MouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("http://www.facebook.com/subtitlestudio"));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelInstructionsDetailLine2MouseClicked

    private void jLabelInstructionsDetailLine3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstructionsDetailLine3MouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("http://www.youtube.com/user/djswap1216/videos"));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelInstructionsDetailLine3MouseClicked

    private void jLabelInstructionsDetailLine4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstructionsDetailLine4MouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("http://subtitlestudio.blogspot.in"));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelInstructionsDetailLine4MouseClicked

    private void jLabelInstructionsDetailLine5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInstructionsDetailLine5MouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("http://www.facebook.com/djswap1216"));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelInstructionsDetailLine5MouseClicked

    private void jLabelFacebookPromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFacebookPromoMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("http://www.facebook.com/subtitlestudio"));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelFacebookPromoMouseClicked

    private void jLabelYouTubePromoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelYouTubePromoMouseClicked
        try {
            Desktop.getDesktop().browse(URI.create("http://www.youtube.com/user/djswap1216/videos"));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelYouTubePromoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrationSubmit;
    private javax.swing.JDialog jDialogUserRegistration;
    private javax.swing.JDialog jDialogWorkInProgress;
    private javax.swing.JLabel jLabelConvert;
    private javax.swing.JLabel jLabelCover;
    private javax.swing.JLabel jLabelCreate;
    private javax.swing.JLabel jLabelDownload;
    private javax.swing.JLabel jLabelFacebookPromo;
    private javax.swing.JLabel jLabelInstructionsDetailLine1;
    private javax.swing.JLabel jLabelInstructionsDetailLine2;
    private javax.swing.JLabel jLabelInstructionsDetailLine3;
    private javax.swing.JLabel jLabelInstructionsDetailLine4;
    private javax.swing.JLabel jLabelInstructionsDetailLine5;
    private javax.swing.JLabel jLabelInstructionsDetailLine6;
    private javax.swing.JLabel jLabelInstructionsDetailLine7;
    private javax.swing.JLabel jLabelInstructionsTitle;
    private javax.swing.JLabel jLabelRegistrationEmail;
    private javax.swing.JLabel jLabelRegistrationFacebookId;
    private javax.swing.JLabel jLabelRegistrationFileWarning;
    private javax.swing.JLabel jLabelRegistrationInstruction;
    private javax.swing.JLabel jLabelRegistrationName;
    private javax.swing.JLabel jLabelRegistrationTitle;
    private javax.swing.JLabel jLabelSelectApp;
    private javax.swing.JLabel jLabelSubApplicationTitle;
    private javax.swing.JLabel jLabelUpload;
    private javax.swing.JLabel jLabelWorkInProgressDetails;
    private javax.swing.JLabel jLabelYouTubePromo;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JPanel jPanelRegistrationParent;
    private javax.swing.JPanel jPanelRegistrationTitle;
    private javax.swing.JPanel jPanelWorkInProgressParent;
    private javax.swing.JTextField jTextFieldRegistrationEmail;
    private javax.swing.JTextField jTextFieldRegistrationFacebookId;
    private javax.swing.JTextField jTextFieldRegistrationName;
    // End of variables declaration//GEN-END:variables
    Creator sync;
    Downloader dwl;
    Convertor cnv;
    Uploader upl;

    public void registerUser() {
        FileReader reader;
        try {
            File f = new File("user.dat");
            reader = new FileReader(f);
            String content = "";
            try {
                int i = reader.read();
                while (i != -1) {
                    content = content + (char) i;
                    i = reader.read();
                }
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    reader.close();
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (FileNotFoundException ex) {
            jDialogUserRegistration.setSize(400, 320);
            jDialogUserRegistration.setLocationRelativeTo(null);
            jDialogUserRegistration.setVisible(true);
        }
    }

    //TODO: Add credentials here
    //DROPBOX
    private static final String APP_KEY = "XXXX";
    private static final String APP_SECRET = "XXXX";
    private static final String AUTH_KEY = "XXXX";
    private static final String AUTH_SECRET = "XXXX";
    private static final Session.AccessType ACCESS_TYPE = Session.AccessType.APP_FOLDER;
    private static DropboxAPI<WebAuthSession> myDropBox;
    public static List<MyServers> servers = new ArrayList<MyServers>(1);
    //END DROPBOX

    int threadNo;

    @Override
    public void run() {
        if (threadNo == 0) {
            jDialogWorkInProgress.setSize(400, 60);
            jDialogWorkInProgress.setLocationRelativeTo(null);
            jDialogWorkInProgress.setVisible(true);
        } else if (threadNo == 1) {
            threadNo = 0;
            new Thread(this).start();

            AppKeyPair appKeys = new AppKeyPair(APP_KEY, APP_SECRET);
            WebAuthSession session = new WebAuthSession(appKeys, ACCESS_TYPE);
            myDropBox = new DropboxAPI<WebAuthSession>(session);
            AccessTokenPair newAuth = new AccessTokenPair(AUTH_KEY, AUTH_SECRET);
            myDropBox.getSession().setAccessTokenPair(newAuth);

            ByteArrayOutputStream outputStream0 = new ByteArrayOutputStream();
            ByteArrayOutputStream outputStream1 = new ByteArrayOutputStream();
            ByteArrayOutputStream outputStream2 = new ByteArrayOutputStream();
            try {
                DropboxAPI.DropboxFileInfo newEntry2 = myDropBox.getFile("/servers/count.txt", null, outputStream0, null);
                DropboxAPI.DropboxFileInfo newEntry3 = myDropBox.getFile("/servers/serverList.txt", null, outputStream1, null);
                DropboxAPI.DropboxFileInfo newEntry4 = myDropBox.getFile("/servers/serverStatus.txt", null, outputStream2, null);

                int count = new Integer(outputStream0.toString());
                String serverList = outputStream1.toString();
                String serverStatus = outputStream2.toString();

                servers.removeAll(servers);
                for (int i = 0; i < (count * 4); i++) {
                    String s[] = serverList.split("\n");
                    MyServers sv = new MyServers(s[i], s[i + 1], s[i + 2], s[i + 3]);
                    servers.add(sv);
                    i = i + 3;
                }
                jDialogWorkInProgress.dispose();
                upl = new Uploader();
                upl.setLocationRelativeTo(null);
                this.setVisible(false);
                upl.setVisible(true);
            } catch (DropboxException ex) {
                jLabelWorkInProgressDetails.setText("Error in Network Connection...");
            }
        } else if (threadNo == 2) {
            threadNo = 0;
            new Thread(this).start();

            AppKeyPair appKeys = new AppKeyPair(APP_KEY, APP_SECRET);
            WebAuthSession session = new WebAuthSession(appKeys, ACCESS_TYPE);
            myDropBox = new DropboxAPI<WebAuthSession>(session);
            AccessTokenPair newAuth = new AccessTokenPair(AUTH_KEY, AUTH_SECRET);
            myDropBox.getSession().setAccessTokenPair(newAuth);

            ByteArrayOutputStream outputStream0 = new ByteArrayOutputStream();
            ByteArrayOutputStream outputStream1 = new ByteArrayOutputStream();
            ByteArrayOutputStream outputStream2 = new ByteArrayOutputStream();
            try {
                DropboxAPI.DropboxFileInfo newEntry2 = myDropBox.getFile("/servers/count.txt", null, outputStream0, null);
                DropboxAPI.DropboxFileInfo newEntry3 = myDropBox.getFile("/servers/serverList.txt", null, outputStream1, null);
                DropboxAPI.DropboxFileInfo newEntry4 = myDropBox.getFile("/servers/serverStatus.txt", null, outputStream2, null);

                int count = new Integer(outputStream0.toString());
                String serverList = outputStream1.toString();
                String serverStatus = outputStream2.toString();

                servers.removeAll(servers);
                for (int i = 0; i < (count * 4); i++) {
                    String s[] = serverList.split("\n");
                    MyServers sv = new MyServers(s[i], s[i + 1], s[i + 2], s[i + 3]);
                    servers.add(sv);
                    i = i + 3;
                }
                jDialogWorkInProgress.dispose();
                dwl = new Downloader();
                dwl.setLocationRelativeTo(null);
                this.setVisible(false);
                dwl.setVisible(true);
            } catch (DropboxException ex) {
                jLabelWorkInProgressDetails.setText("Error in Network Connection...");
            }
        }
    }
}
