/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.swapnilbhoite.projects.subtitlestudio;

import java.awt.Frame;

/**
 *
 * @author Swapnil Bhoite
 */
public class ProgressDialog extends javax.swing.JDialog implements Runnable {

    private String message = "";

    /**
     * Creates new form ProgressDialog
     *
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public ProgressDialog() {
        super(new Frame(), true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Please wait...");
    }

    public void showDialog() {
        showDialog("Some work in progress...");
    }

    public void showDialog(String message) {
        this.message = message;
        new Thread(this).start();
    }

    public void hideDialog() {
        this.setVisible(false);
    }

    @Override
    public void run() {
        this.setVisible(false);
        this.jLabelProgressMessage.setText(message);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProgressDialogParent = new javax.swing.JPanel();
        jPanelProgressDialogBody = new javax.swing.JPanel();
        jLabelProgressMessage = new javax.swing.JLabel();
        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelProgressDialogParent.setBackground(new java.awt.Color(51, 51, 51));

        jPanelProgressDialogBody.setBackground(new java.awt.Color(0, 0, 0));

        jLabelProgressMessage.setBackground(java.awt.Color.black);
        jLabelProgressMessage.setForeground(java.awt.Color.white);
        jLabelProgressMessage.setText("Please wait...");

        jProgressBar.setIndeterminate(true);

        javax.swing.GroupLayout jPanelProgressDialogBodyLayout = new javax.swing.GroupLayout(jPanelProgressDialogBody);
        jPanelProgressDialogBody.setLayout(jPanelProgressDialogBodyLayout);
        jPanelProgressDialogBodyLayout.setHorizontalGroup(
            jPanelProgressDialogBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressDialogBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProgressDialogBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelProgressMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelProgressDialogBodyLayout.setVerticalGroup(
            jPanelProgressDialogBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressDialogBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelProgressMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelProgressDialogParentLayout = new javax.swing.GroupLayout(jPanelProgressDialogParent);
        jPanelProgressDialogParent.setLayout(jPanelProgressDialogParentLayout);
        jPanelProgressDialogParentLayout.setHorizontalGroup(
            jPanelProgressDialogParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressDialogParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProgressDialogBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProgressDialogParentLayout.setVerticalGroup(
            jPanelProgressDialogParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProgressDialogParentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProgressDialogBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProgressDialogParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelProgressDialogParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelProgressMessage;
    private javax.swing.JPanel jPanelProgressDialogBody;
    private javax.swing.JPanel jPanelProgressDialogParent;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
